# Generated by Django 5.0.8 on 2024-09-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0154_merge_20240916_1041"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
            ],
            options={
                "verbose_name": "ingrédient",
                "verbose_name_plural": "ingrédients",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="titre")),
                ("instructions", models.TextField(verbose_name="instructions")),
                ("cooking_time", models.DurationField(verbose_name="temps de cuisson")),
                (
                    "ingredients",
                    models.ManyToManyField(
                        to="data.ingredient", verbose_name="ingrédients"
                    ),
                ),
            ],
            options={
                "verbose_name": "recette",
                "verbose_name_plural": "recettes",
            },
        ),
    ]
