# Generated by Django 5.0.8 on 2024-09-23 00:27

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0154_merge_20240916_1041"),
        ("djf_surveys", "0017_alter_survey_success_page_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
            ],
            options={
                "verbose_name": "ingrédient",
                "verbose_name_plural": "ingrédients",
            },
        ),
        migrations.AddField(
            model_name="canteen",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                related_name="joined_canteens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="clients",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="job",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESTABLISHMENT_MANAGER", "Gestionnaire d'établissement"),
                    (
                        "CATERING_PURCHASES_MANAGER",
                        "Direction Achat Société de restauration",
                    ),
                    (
                        "DIRECT_PURCHASES_MANAGER",
                        "Responsable d'achats en gestion directe",
                    ),
                    (
                        "CENTRAL_MANAGER",
                        "Responsable de plusieurs établissements (type cuisine centrale)",
                    ),
                    (
                        "MANY_ESTABLISHMENTS_MANAGER",
                        "Responsable de plusieurs établissements (SRC)",
                    ),
                    (
                        "TECHNICAL",
                        "Développement logiciel, analyse de données ou autre rôle technique",
                    ),
                    ("OTHER", "Autre"),
                    ("CLIENT", "Client"),
                ],
                max_length=255,
                null=True,
                verbose_name="Fonction",
            ),
        ),
        migrations.CreateModel(
            name="CanteenSurvey",
            fields=[
                (
                    "survey_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="djf_surveys.survey",
                    ),
                ),
                (
                    "canteen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="data.canteen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sondage lié à une cantine",
                "verbose_name_plural": "Sondages liés aux cantines",
                "ordering": ["canteen"],
            },
            bases=("djf_surveys.survey",),
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="titre")),
                (
                    "instructions",
                    ckeditor.fields.RichTextField(
                        default="<ul><li>Etape 1 : </li><li>Etape 2 : </li></ul><p>Bon appétit !</p>",
                        verbose_name="Instructions",
                    ),
                ),
                ("cooking_time", models.DurationField(verbose_name="temps de cuisson")),
                ("survey_link", models.URLField(blank=True, null=True)),
                (
                    "ingredients",
                    models.ManyToManyField(
                        to="data.ingredient", verbose_name="ingrédients"
                    ),
                ),
            ],
            options={
                "verbose_name": "recette",
                "verbose_name_plural": "recettes",
            },
        ),
    ]
