# Generated by Django 5.0.8 on 2024-09-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0155_ingredient_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="job",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESTABLISHMENT_MANAGER", "Gestionnaire d'établissement"),
                    (
                        "CATERING_PURCHASES_MANAGER",
                        "Direction Achat Société de restauration",
                    ),
                    (
                        "DIRECT_PURCHASES_MANAGER",
                        "Responsable d'achats en gestion directe",
                    ),
                    (
                        "CENTRAL_MANAGER",
                        "Responsable de plusieurs établissements (type cuisine centrale)",
                    ),
                    (
                        "MANY_ESTABLISHMENTS_MANAGER",
                        "Responsable de plusieurs établissements (SRC)",
                    ),
                    (
                        "TECHNICAL",
                        "Développement logiciel, analyse de données ou autre rôle technique",
                    ),
                    ("OTHER", "Autre"),
                    ("CLIENT", "Client"),
                ],
                max_length=255,
                null=True,
                verbose_name="Fonction",
            ),
        ),
    ]
