# Generated by Django 5.0.8 on 2024-09-19 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0156_alter_user_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                related_name="joined_canteens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="clients",
            ),
        ),
    ]
