# Generated by Django 5.0.8 on 2024-09-22 17:20

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0157_canteen_clients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="survey_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=ckeditor.fields.RichTextField(
                default="<ul><li>Etape 1 : </li><li>Etape 2 : </li></ul><p>Bon appétit !</p>",
                verbose_name="Instructions",
            ),
        ),
        migrations.CreateModel(
            name="CanteenSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("survey_link", models.URLField()),
                (
                    "canteen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.canteen"
                    ),
                ),
            ],
        ),
    ]
